# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yP4iNP2agsRe4wEYgsEg67rfMsFKiPZe
"""

#importamos las librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import seaborn as sns
import pickle

#cargamos el dataset

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

print("Primeras filas del dataset:")
display(X.head())

#realizacion de un analisis exploratorio

sns.pairplot(pd.concat([X, pd.DataFrame({"species": y})], axis=1), hue="species")
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(X.corr(), annot=True, cmap="viridis")
plt.title("Matriz de correlación")
plt.show()

#entrenamiento y prueba

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#entrenamos el modelo

model = RandomForestClassifier(n_estimators=150, random_state=42)
model.fit(X_train, y_train)

#predicciones

y_pred = model.predict(X_test)

#metricas del modelo

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
f1 = f1_score(y_test, y_pred, average="weighted")

print("\n======= Métricas del Modelo =======")
print(f"Accuracy: {acc:.4f}")
print(f"Precision (weighted): {prec:.4f}")
print(f"Recall (weighted): {recall:.4f}")
print(f"F1-score (weighted): {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

#guardar modelo

with open("modelo_iris.pkl", "wb") as f:
    pickle.dump(model, f)

print("\nModelo guardado como: modelo_iris.pkl")
